# Generated by Django 5.2.16 on 2026-09-17 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0105_authority_pack_artifacts"),
        ("documents", "0046_ingestion_run_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationVersionDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("REAPPROVED", "Re-approved on the new version"),
                            ("CORRECTED", "Corrected on the new version"),
                            ("DROPPED", "No longer applies"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        help_text="The human annotation on the superseded (previous) version.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_decisions",
                        to="annotations.annotation",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The ordinary annotation created on the new version, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carried_from_decisions",
                        to="annotations.annotation",
                    ),
                ),
                (
                    "target_document",
                    models.ForeignKey(
                        help_text="The newer version the annotation was reviewed against.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_version_decisions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["target_document", "decision"],
                        name="ann_ver_decision_target_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("annotation", "target_document"),
                        name="uniq_annotation_version_decision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("decision__in", ("REAPPROVED", "CORRECTED", "DROPPED"))
                        ),
                        name="annotation_version_decision_valid",
                    ),
                ],
            },
        ),
    ]
