# Generated by Django 5.2.16 on 2026-09-17 06:56

from itertools import batched

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models.functions import Coalesce


def pin_existing_mention_links(apps, schema_editor):
    """Repair old stored URLs even for corpora with no external refs to relink."""
    Reference = apps.get_model("annotations", "CorpusReference")
    Annotation = apps.get_model("annotations", "Annotation")
    Path = apps.get_model("documents", "DocumentPath")
    db = schema_editor.connection.alias
    versions = (
        Path.objects.using(db)
        .filter(
            document_id=models.OuterRef("target_document_id"),
            corpus_id=Coalesce(
                models.OuterRef("target_corpus_id"), models.OuterRef("corpus_id")
            ),
        )
        .order_by("-created")
        .values("version_number")[:1]
    )
    refs = (
        Reference.objects.using(db)
        .filter(
            reference_type__in=["LAW", "DOCUMENT"],
            resolution_status="RESOLVED",
            target_document__isnull=False,
        )
        .annotate(pinned_version=models.Subquery(versions))
        .filter(
            pinned_version__isnull=False,
        )
        .select_related(
            "source_annotation",
            "target_document",
            "target_corpus__creator",
            "corpus__creator",
        )
    )
    for batch in batched(refs.iterator(chunk_size=500), 500):
        changed = {}
        for ref in batch:
            corpus = ref.target_corpus or ref.corpus
            if not all((corpus.creator.slug, corpus.slug, ref.target_document.slug)):
                continue
            url = f"/d/{corpus.creator.slug}/{corpus.slug}/{ref.target_document.slug}?v={ref.pinned_version}"
            if ref.source_annotation.link_url != url:
                ref.source_annotation.link_url = url
                changed[ref.source_annotation_id] = ref.source_annotation
        Annotation.objects.using(db).bulk_update(changed.values(), ["link_url"])


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0105_authority_pack_artifacts"),
        ("documents", "0046_ingestion_run_policy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationVersionDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("REAPPROVED", "Re-approved"),
                            ("CORRECTED", "Corrected"),
                            ("DROPPED", "Dropped"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="version_decisions",
                        to="annotations.annotation",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predecessor_decisions",
                        to="annotations.annotation",
                    ),
                ),
                (
                    "target_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_version_decisions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("annotation", "target_document"),
                        name="unique_annotation_version_decision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("decision__in", ["REAPPROVED", "CORRECTED", "DROPPED"])
                        ),
                        name="annotation_version_decision_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(pin_existing_mention_links, migrations.RunPython.noop),
    ]
