# Generated by Claude Code on 2025-11-09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def migrate_existing_corpus_documents(apps, schema_editor):
    """
    Migrate existing corpus-document relationships to the new through model.
    All existing relationships will be placed at root level (path="").
    """
    Corpus = apps.get_model("corpuses", "Corpus")
    CorpusDocumentAssociation = apps.get_model("corpuses", "CorpusDocumentAssociation")

    # Get the old through model
    db_alias = schema_editor.connection.alias

    # The old through table is named corpuses_corpus_documents
    # We'll query it directly to migrate the data
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            INSERT INTO corpuses_corpusdocumentassociation (corpus_id, document_id, path, created, modified)
            SELECT corpus_id, document_id, '', NOW(), NOW()
            FROM corpuses_corpus_documents
            ON CONFLICT DO NOTHING
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0022_add_agent_instructions"),
        ("documents", "0001_initial"),  # Ensure Document model exists
    ]

    operations = [
        # Create the new through model
        migrations.CreateModel(
            name="CorpusDocumentAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Virtual folder path for this document in the corpus. Use forward slashes with leading/trailing slashes (e.g., '/folder/subfolder/'). Empty string or '/' represents root level.",
                        max_length=1024,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "modified",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "corpus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_associations",
                        to="corpuses.corpus",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corpus_associations",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ("path", "document__title"),
            },
        ),
        # Add indexes
        migrations.AddIndex(
            model_name="corpusdocumentassociation",
            index=models.Index(fields=["corpus", "path"], name="corpuses_co_corpus__be0f09_idx"),
        ),
        migrations.AddIndex(
            model_name="corpusdocumentassociation",
            index=models.Index(fields=["document"], name="corpuses_co_documen_6e0b25_idx"),
        ),
        migrations.AddIndex(
            model_name="corpusdocumentassociation",
            index=models.Index(fields=["path"], name="corpuses_co_path_7c9d7e_idx"),
        ),
        migrations.AddIndex(
            model_name="corpusdocumentassociation",
            index=models.Index(fields=["created"], name="corpuses_co_created_8a1b2c_idx"),
        ),
        # Add unique constraint
        migrations.AlterUniqueTogether(
            name="corpusdocumentassociation",
            unique_together={("corpus", "document")},
        ),
        # Migrate existing data BEFORE altering the Corpus.documents field
        migrations.RunPython(
            migrate_existing_corpus_documents,
            reverse_code=migrations.RunPython.noop,
        ),
        # Now alter the Corpus.documents field to use the through model
        migrations.AlterField(
            model_name="corpus",
            name="documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="corpuses_via_associations",
                through="corpuses.CorpusDocumentAssociation",
                to="documents.document",
            ),
        ),
    ]
