# Generated by Django 5.2.13 on 2026-05-12 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0048_corpus_agent_memory"),
        ("documents", "0037_add_default_reranker_to_pipeline_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="documentpath",
            index=models.Index(
                fields=["document", "corpus", "is_current", "is_deleted"],
                name="documents_d_documen_224610_idx",
            ),
        ),
    ]
