# Generated by Django 5.2.13 on 2026-05-12 02:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corpuses", "0048_corpus_agent_memory"),
        ("documents", "0037_add_default_reranker_to_pipeline_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentpath",
            new_name="documents_d_ingesti_a834a5_idx",
            old_name="documents_d_ingesti_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="ingestionsource",
            new_name="documents_i_source__bc23a9_idx",
            old_name="documents_i_source__5c7a8e_idx",
        ),
        migrations.RenameIndex(
            model_name="ingestionsource",
            new_name="documents_i_active_6dc4ee_idx",
            old_name="documents_i_active_3f1b2a_idx",
        ),
        migrations.AddIndex(
            model_name="documentpath",
            index=models.Index(
                fields=["document", "corpus", "is_current", "is_deleted"],
                name="documents_d_documen_224610_idx",
            ),
        ),
    ]
